// Audit actions in words, for the overview's "Последние события" and the
// audit tab. An action missing here shows as itself — still true, just terse.
const LABELS: Record<string, string> = {
  "user.bootstrap": "Создан первый CEO",
  "user.registered": "Новый пользователь",
  "user.login": "Вход",
  "user.login_failed": "Неудачный вход",
  "user.locked": "Вход заблокирован после неудачных попыток",
  "user.logout": "Выход",
  "user.logout_all": "Выход со всех устройств",
  "user.password_changed": "Смена пароля",
  "user.password_reset": "Пароль сброшен администратором",
  "user.username_changed": "Смена логина",
  "user.activated": "Аккаунт включён",
  "user.deactivated": "Аккаунт отключён",
  "user.verified": "Выдана галочка",
  "user.unverified": "Снята галочка",
  "user.consent_accepted": "Приняты политика и правила",
  "user.delete_self": "Аккаунт удалён владельцем",
  "user.block": "Блокировка пользователя",
  "user.unblock": "Снята блокировка",
  "invite.created": "Создано приглашение",
  "invite.used": "Использовано приглашение",
  "role.changed": "Изменена роль",
  "session.refresh_reuse_detected": "Повтор refresh-токена — сессии отозваны",
  "message.forwarded": "Пересылка сообщения",
  "group.created": "Создана группа",
  "group.deleted": "Удалена группа",
  "group.verified": "Сообществу выдана галочка",
  "group.unverified": "У сообщества снята галочка",
  "group.warned": "Предупреждение сообществу",
  "group.muted": "Сообщество замучено",
  "group.moderation_deleted": "Сообщество удалено модерацией",
  "group.restored": "Сообщество восстановлено",
  "group.sanction_revoked": "Санкция снята",
  "group.purged": "Сообщество удалено окончательно",
  "report.create": "Новая жалоба",
  "report.bin": "Жалоба закрыта",
  "announcement.sent": "Уведомление от руководства",
  "announcement.revoked": "Уведомление отозвано",
  "release.announced": "Объявлена новая версия",
  "call.started": "Звонок",
  "call.answered": "Звонок принят",
  "call.busy": "Звонок: абонент занят",
};

export function auditLabel(action: string): string {
  return LABELS[action] ?? action;
}
